from enum import IntEnum
from typing import Annotated, SupportsInt

import numpy
from numpy.typing import ArrayLike, NDArray

class EpisodeState(IntEnum):
    Alive = 0
    OutOfBound = 1
    MissileCollision = 2
    Timeout = 3

class Simulation:
    def __init__(
        self,
        timeout: SupportsInt,
        action_period: int = 2,
        window_size: tuple[SupportsInt, SupportsInt] | None = None,
    ) -> None: ...

    def get_obs(self) -> NDArray[numpy.float32]: ...
    def get_episode_state(self) -> EpisodeState: ...
    def get_reward_list(self) -> list[float]: ...
    def get_reward(self) -> float: ...
    
    def step(self, action: Annotated[ArrayLike, numpy.int32]) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
    def render(self) -> None: ...
    def close(self) -> None: ...


def get_action_from_keyboard() -> tuple[bool, bool, bool]: ...

def window_should_close() -> bool: ...
